BGX += 0.5;
surf = check_surface(surf, 895.999968, 140.16 * borderscaleYmult);
clip = check_surface(clip, 895.999968, 140.16 * borderscaleYmult);
surface_set_target(surf);
draw_sprite_tiled(spr_grannymugBG, 0, BGX, BGX);
surface_reset_target();
surface_set_target(clip);
draw_clear(c_white);
gpu_set_blendmode(bm_subtract);
draw_sprite_ext(spr_borderNPC, 1, 0, 0, 9.333333, 1.45 * borderscaleYmult, 0, c_white, 1);
surface_reset_target();
surface_set_target(surf);
draw_surface(clip, 0, 0);
gpu_set_blendmode(bm_normal);
surface_reset_target();
draw_surface(surf, borderX, borderY);
draw_sprite_ext(spr_borderNPC, 0, borderX, borderY, 9.333333, 1.45 * borderscaleYmult, 0, c_white, 1);
draw_set_color(c_black);
draw_set_font(global.npcfont);
draw_set_halign(fa_left);
maynia_draw_text(borderX + 16, borderY + 10, "/s" + text, 64);
draw_set_color(c_white);
