// Generated by Ultimate_GMS2_Decompiler_v3.csx
gml_pragma("global", @'global.__gameframe_buffer = undefined');
gml_pragma("global", @'global.__ggpo_string_buffer = undefined');

// GameSpecificData Enums
enum e__VW 
{
	XView = 0,
	YView = 1,
	WView = 2,
	HView = 3,
	Angle = 4,
	HBorder = 5,
	VBorder = 6,
	HSpeed = 7,
	VSpeed = 8,
	Object = 9,
	Visible = 10,
	XPort = 11,
	YPort = 12,
	WPort = 13,
	HPort = 14,
	Camera = 15,
	SurfaceID = 16,
}

enum e__BG 
{
	Visible = 0,
	Foreground = 1,
	Index = 2,
	X = 3,
	Y = 4,
	Width = 5,
	Height = 6,
	HTiled = 7,
	VTiled = 8,
	XScale = 9,
	YScale = 10,
	HSpeed = 11,
	VSpeed = 12,
	Blend = 13,
	Alpha = 14,
}

// Generic Enum Declaration
enum UnknownEnum 
{
	Value_0,
	Value_1,
	Value_2,
	Value_3,
	Value_4,
	Value_5,
	Value_6,
	Value_7,
	Value_8,
	Value_9,
	Value_10,
	Value_11,
	Value_12,
	Value_13,
	Value_14,
	Value_15,
	Value_16,
	Value_17,
	Value_18,
	Value_19,
	Value_20,
	Value_21,
	Value_22,
	Value_23,
	Value_24,
	Value_25,
	Value_26,
	Value_27,
	Value_28,
	Value_29,
	Value_30,
	Value_31,
	Value_32,
	Value_33,
	Value_34,
	Value_35,
	Value_36,
	Value_38 = 38,
	Value_39,
}