camera_set_view_size(view_camera[0], obj_screensizer.displayWidth, obj_screensizer.displayHeight);
global.collectfont = __scribble_font_add_sprite_ext(font_collecthud, "0123456789", 1, 0);
global.creditsfont = __scribble_font_add_sprite_ext(spr_creditsfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.:!0123456789?'\"ÁÉÍÓÚáéíóú_-[]▼()&#风雨廊桥전태양*яиБжидГзвбнль↑↓←→⇧⌃␣⎋", 1, 2);
global.buttonfont = __scribble_font_add_sprite_ext(spr_buttonfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!,.:0123456789'?-↑↓←→⇧¢␣⎋", 1, 2);
global.bigfont = __scribble_font_add_sprite_ext(spr_bigfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0);
global.smallfont = __scribble_font_add_sprite_ext(spr_smallfont, "abcdefghijklmnopqrstuvqxyz1234567890.:!?", 1, 0);
global.npcfont = __scribble_font_add_sprite_ext(spr_npcfont, "ABCDEFGHIJKLMNÑOPQRSTUVWXYZabcdefghijklmnñopqrstuvwxyz!¡,.:0123456789'?¿-áäãàâæéèêëíîïóöõôúùûüÿŸÁÄÃÀÂÉÈÊËÍÎÏÓÖÕÔÚÙÛÜÇç", true, 2);
global.moneyfont = __scribble_font_add_sprite_ext(spr_moneyfont, "0123456789$-", 1, 0);
global.smallnumberfnt = __scribble_font_add_sprite_ext(spr_smallnumber, "1234567890-+", 1, 0);
global.combofont = __scribble_font_add_sprite_ext(spr_combofont, "0123456789", 1, 0);
global.showcollisions = false;
global.debug = false;
lang_start();
scr_mayniaInput();
ini_open("options.ini");
global.MasterVolume = ini_read_real("General", "Master", 1);
global.MusicVolume = ini_read_real("General", "Music", 1);
global.SfxVolume = ini_read_real("General", "Sfx", 0.7);
global.Fullscreen = ini_read_real("General", "Fullscreen", false);
window_set_fullscreen(global.Fullscreen);
global.Vsync = ini_read_real("General", "Vsync", false);
global.hide_hud = ini_read_real("Visual", "hud", false);
global.saveFile = 1;
ini_close();
pal_swap_init_system(shd_pal_swapper);
room = rm_intro;
obj_player.targetDoor = "A";
